included:
 - Sources
 - Tests
disabled_rules:
- nesting
- legacy_hashing
- inclusive_language
identifier_name:
  excluded:
    - i
    - j
    - id
    - cp
    - xp
    - ex
    - iv
type_name:
  excluded:
    - IV
