language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swiftenv install
  - git clone https://github.com/realm/SwiftLint SwiftLint && git submodule update --init --recursive && swiftenv install && make && cd .. && rm -rf SwiftLint
script:
  - swiftlint
  - swift test
