// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Platform/PlatformRequestType.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum POGOProtos_Networking_Platform_PlatformRequestType: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case methodUnset // = 0
  case buyItemPokecoins // = 2
  case buyItemAndroid // = 3
  case buyItemIos // = 4
  case getStoreItems // = 5
  case sendEncryptedSignature // = 6
  case unknownPtr8 // = 8
  case joinEvent // = 9
  case UNRECOGNIZED(Int)

  init() {
    self = .methodUnset
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .methodUnset
    case 2: self = .buyItemPokecoins
    case 3: self = .buyItemAndroid
    case 4: self = .buyItemIos
    case 5: self = .getStoreItems
    case 6: self = .sendEncryptedSignature
    case 8: self = .unknownPtr8
    case 9: self = .joinEvent
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .methodUnset: return 0
    case .buyItemPokecoins: return 2
    case .buyItemAndroid: return 3
    case .buyItemIos: return 4
    case .getStoreItems: return 5
    case .sendEncryptedSignature: return 6
    case .unknownPtr8: return 8
    case .joinEvent: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension POGOProtos_Networking_Platform_PlatformRequestType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Networking_Platform_PlatformRequestType] = [
    .methodUnset,
    .buyItemPokecoins,
    .buyItemAndroid,
    .buyItemIos,
    .getStoreItems,
    .sendEncryptedSignature,
    .unknownPtr8,
    .joinEvent,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension POGOProtos_Networking_Platform_PlatformRequestType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "METHOD_UNSET"),
    2: .same(proto: "BUY_ITEM_POKECOINS"),
    3: .same(proto: "BUY_ITEM_ANDROID"),
    4: .same(proto: "BUY_ITEM_IOS"),
    5: .same(proto: "GET_STORE_ITEMS"),
    6: .same(proto: "SEND_ENCRYPTED_SIGNATURE"),
    8: .same(proto: "UNKNOWN_PTR_8"),
    9: .same(proto: "JOIN_EVENT"),
  ]
}
