// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Requests/Messages/FortSearchMessage.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Networking_Requests_Messages_FortSearchMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fortID: String = String()

  var playerLatitude: Double = 0

  var playerLongitude: Double = 0

  var fortLatitude: Double = 0

  var fortLongitude: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Requests.Messages"

extension POGOProtos_Networking_Requests_Messages_FortSearchMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FortSearchMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "fort_id"),
    2: .standard(proto: "player_latitude"),
    3: .standard(proto: "player_longitude"),
    4: .standard(proto: "fort_latitude"),
    5: .standard(proto: "fort_longitude"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.fortID)
      case 2: try decoder.decodeSingularDoubleField(value: &self.playerLatitude)
      case 3: try decoder.decodeSingularDoubleField(value: &self.playerLongitude)
      case 4: try decoder.decodeSingularDoubleField(value: &self.fortLatitude)
      case 5: try decoder.decodeSingularDoubleField(value: &self.fortLongitude)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fortID.isEmpty {
      try visitor.visitSingularStringField(value: self.fortID, fieldNumber: 1)
    }
    if self.playerLatitude != 0 {
      try visitor.visitSingularDoubleField(value: self.playerLatitude, fieldNumber: 2)
    }
    if self.playerLongitude != 0 {
      try visitor.visitSingularDoubleField(value: self.playerLongitude, fieldNumber: 3)
    }
    if self.fortLatitude != 0 {
      try visitor.visitSingularDoubleField(value: self.fortLatitude, fieldNumber: 4)
    }
    if self.fortLongitude != 0 {
      try visitor.visitSingularDoubleField(value: self.fortLongitude, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Networking_Requests_Messages_FortSearchMessage, rhs: POGOProtos_Networking_Requests_Messages_FortSearchMessage) -> Bool {
    if lhs.fortID != rhs.fortID {return false}
    if lhs.playerLatitude != rhs.playerLatitude {return false}
    if lhs.playerLongitude != rhs.playerLongitude {return false}
    if lhs.fortLatitude != rhs.fortLatitude {return false}
    if lhs.fortLongitude != rhs.fortLongitude {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
