// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/GetIncensePokemonResponse.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Networking_Responses_GetIncensePokemonResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: POGOProtos_Networking_Responses_GetIncensePokemonResponse.Result {
    get {return _storage._result}
    set {_uniqueStorage()._result = newValue}
  }

  var pokemonID: POGOProtos_Enums_PokemonId {
    get {return _storage._pokemonID}
    set {_uniqueStorage()._pokemonID = newValue}
  }

  var latitude: Double {
    get {return _storage._latitude}
    set {_uniqueStorage()._latitude = newValue}
  }

  var longitude: Double {
    get {return _storage._longitude}
    set {_uniqueStorage()._longitude = newValue}
  }

  var encounterLocation: String {
    get {return _storage._encounterLocation}
    set {_uniqueStorage()._encounterLocation = newValue}
  }

  var encounterID: UInt64 {
    get {return _storage._encounterID}
    set {_uniqueStorage()._encounterID = newValue}
  }

  var disappearTimestampMs: Int64 {
    get {return _storage._disappearTimestampMs}
    set {_uniqueStorage()._disappearTimestampMs = newValue}
  }

  var pokemonDisplay: POGOProtos_Data_PokemonDisplay {
    get {return _storage._pokemonDisplay ?? POGOProtos_Data_PokemonDisplay()}
    set {_uniqueStorage()._pokemonDisplay = newValue}
  }
  /// Returns true if `pokemonDisplay` has been explicitly set.
  var hasPokemonDisplay: Bool {return _storage._pokemonDisplay != nil}
  /// Clears the value of `pokemonDisplay`. Subsequent reads from it will return its default value.
  mutating func clearPokemonDisplay() {_uniqueStorage()._pokemonDisplay = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Result: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case incenseEncounterUnknown // = 0
    case incenseEncounterAvailable // = 1
    case incenseEncounterNotAvailable // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .incenseEncounterUnknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .incenseEncounterUnknown
      case 1: self = .incenseEncounterAvailable
      case 2: self = .incenseEncounterNotAvailable
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .incenseEncounterUnknown: return 0
      case .incenseEncounterAvailable: return 1
      case .incenseEncounterNotAvailable: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_GetIncensePokemonResponse.Result: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Networking_Responses_GetIncensePokemonResponse.Result] = [
    .incenseEncounterUnknown,
    .incenseEncounterAvailable,
    .incenseEncounterNotAvailable,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_GetIncensePokemonResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetIncensePokemonResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
    2: .standard(proto: "pokemon_id"),
    3: .same(proto: "latitude"),
    4: .same(proto: "longitude"),
    5: .standard(proto: "encounter_location"),
    6: .standard(proto: "encounter_id"),
    7: .standard(proto: "disappear_timestamp_ms"),
    8: .standard(proto: "pokemon_display"),
  ]

  fileprivate class _StorageClass {
    var _result: POGOProtos_Networking_Responses_GetIncensePokemonResponse.Result = .incenseEncounterUnknown
    var _pokemonID: POGOProtos_Enums_PokemonId = .missingno
    var _latitude: Double = 0
    var _longitude: Double = 0
    var _encounterLocation: String = String()
    var _encounterID: UInt64 = 0
    var _disappearTimestampMs: Int64 = 0
    var _pokemonDisplay: POGOProtos_Data_PokemonDisplay? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _result = source._result
      _pokemonID = source._pokemonID
      _latitude = source._latitude
      _longitude = source._longitude
      _encounterLocation = source._encounterLocation
      _encounterID = source._encounterID
      _disappearTimestampMs = source._disappearTimestampMs
      _pokemonDisplay = source._pokemonDisplay
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularEnumField(value: &_storage._result)
        case 2: try decoder.decodeSingularEnumField(value: &_storage._pokemonID)
        case 3: try decoder.decodeSingularDoubleField(value: &_storage._latitude)
        case 4: try decoder.decodeSingularDoubleField(value: &_storage._longitude)
        case 5: try decoder.decodeSingularStringField(value: &_storage._encounterLocation)
        case 6: try decoder.decodeSingularFixed64Field(value: &_storage._encounterID)
        case 7: try decoder.decodeSingularInt64Field(value: &_storage._disappearTimestampMs)
        case 8: try decoder.decodeSingularMessageField(value: &_storage._pokemonDisplay)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._result != .incenseEncounterUnknown {
        try visitor.visitSingularEnumField(value: _storage._result, fieldNumber: 1)
      }
      if _storage._pokemonID != .missingno {
        try visitor.visitSingularEnumField(value: _storage._pokemonID, fieldNumber: 2)
      }
      if _storage._latitude != 0 {
        try visitor.visitSingularDoubleField(value: _storage._latitude, fieldNumber: 3)
      }
      if _storage._longitude != 0 {
        try visitor.visitSingularDoubleField(value: _storage._longitude, fieldNumber: 4)
      }
      if !_storage._encounterLocation.isEmpty {
        try visitor.visitSingularStringField(value: _storage._encounterLocation, fieldNumber: 5)
      }
      if _storage._encounterID != 0 {
        try visitor.visitSingularFixed64Field(value: _storage._encounterID, fieldNumber: 6)
      }
      if _storage._disappearTimestampMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._disappearTimestampMs, fieldNumber: 7)
      }
      if let v = _storage._pokemonDisplay {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Networking_Responses_GetIncensePokemonResponse, rhs: POGOProtos_Networking_Responses_GetIncensePokemonResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._result != rhs_storage._result {return false}
        if _storage._pokemonID != rhs_storage._pokemonID {return false}
        if _storage._latitude != rhs_storage._latitude {return false}
        if _storage._longitude != rhs_storage._longitude {return false}
        if _storage._encounterLocation != rhs_storage._encounterLocation {return false}
        if _storage._encounterID != rhs_storage._encounterID {return false}
        if _storage._disappearTimestampMs != rhs_storage._disappearTimestampMs {return false}
        if _storage._pokemonDisplay != rhs_storage._pokemonDisplay {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_GetIncensePokemonResponse.Result: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "INCENSE_ENCOUNTER_UNKNOWN"),
    1: .same(proto: "INCENSE_ENCOUNTER_AVAILABLE"),
    2: .same(proto: "INCENSE_ENCOUNTER_NOT_AVAILABLE"),
  ]
}
