// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/GetMapObjectsResponse.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Networking_Responses_GetMapObjectsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var mapCells: [POGOProtos_Map_MapCell] = []

  var status: POGOProtos_Map_MapObjectsStatus = .unsetStatus

  var timeOfDay: POGOProtos_Networking_Responses_GetMapObjectsResponse.TimeOfDay = .none

  var clientWeather: [POGOProtos_Map_Weather_ClientWeather] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum TimeOfDay: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case none // = 0
    case day // = 1
    case night // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .none
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .none
      case 1: self = .day
      case 2: self = .night
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .none: return 0
      case .day: return 1
      case .night: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_GetMapObjectsResponse.TimeOfDay: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Networking_Responses_GetMapObjectsResponse.TimeOfDay] = [
    .none,
    .day,
    .night,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_GetMapObjectsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMapObjectsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "map_cells"),
    2: .same(proto: "status"),
    3: .standard(proto: "time_of_day"),
    4: .standard(proto: "client_weather"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.mapCells)
      case 2: try decoder.decodeSingularEnumField(value: &self.status)
      case 3: try decoder.decodeSingularEnumField(value: &self.timeOfDay)
      case 4: try decoder.decodeRepeatedMessageField(value: &self.clientWeather)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mapCells.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.mapCells, fieldNumber: 1)
    }
    if self.status != .unsetStatus {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    if self.timeOfDay != .none {
      try visitor.visitSingularEnumField(value: self.timeOfDay, fieldNumber: 3)
    }
    if !self.clientWeather.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.clientWeather, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Networking_Responses_GetMapObjectsResponse, rhs: POGOProtos_Networking_Responses_GetMapObjectsResponse) -> Bool {
    if lhs.mapCells != rhs.mapCells {return false}
    if lhs.status != rhs.status {return false}
    if lhs.timeOfDay != rhs.timeOfDay {return false}
    if lhs.clientWeather != rhs.clientWeather {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_GetMapObjectsResponse.TimeOfDay: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NONE"),
    1: .same(proto: "DAY"),
    2: .same(proto: "NIGHT"),
  ]
}
