// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Networking/Responses/SetBuddyPokemonResponse.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Networking_Responses_SetBuddyPokemonResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: POGOProtos_Networking_Responses_SetBuddyPokemonResponse.Result {
    get {return _storage._result}
    set {_uniqueStorage()._result = newValue}
  }

  var updatedBuddy: POGOProtos_Data_BuddyPokemon {
    get {return _storage._updatedBuddy ?? POGOProtos_Data_BuddyPokemon()}
    set {_uniqueStorage()._updatedBuddy = newValue}
  }
  /// Returns true if `updatedBuddy` has been explicitly set.
  var hasUpdatedBuddy: Bool {return _storage._updatedBuddy != nil}
  /// Clears the value of `updatedBuddy`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedBuddy() {_uniqueStorage()._updatedBuddy = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Result: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case unest // = 0
    case success // = 1
    case errorPokemonDeployed // = 2
    case errorPokemonNotOwned // = 3
    case errorPokemonIsEgg // = 4
    case errorInvalidPokemon // = 5
    case UNRECOGNIZED(Int)

    init() {
      self = .unest
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unest
      case 1: self = .success
      case 2: self = .errorPokemonDeployed
      case 3: self = .errorPokemonNotOwned
      case 4: self = .errorPokemonIsEgg
      case 5: self = .errorInvalidPokemon
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unest: return 0
      case .success: return 1
      case .errorPokemonDeployed: return 2
      case .errorPokemonNotOwned: return 3
      case .errorPokemonIsEgg: return 4
      case .errorInvalidPokemon: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension POGOProtos_Networking_Responses_SetBuddyPokemonResponse.Result: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Networking_Responses_SetBuddyPokemonResponse.Result] = [
    .unest,
    .success,
    .errorPokemonDeployed,
    .errorPokemonNotOwned,
    .errorPokemonIsEgg,
    .errorInvalidPokemon,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Networking.Responses"

extension POGOProtos_Networking_Responses_SetBuddyPokemonResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetBuddyPokemonResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
    2: .standard(proto: "updated_buddy"),
  ]

  fileprivate class _StorageClass {
    var _result: POGOProtos_Networking_Responses_SetBuddyPokemonResponse.Result = .unest
    var _updatedBuddy: POGOProtos_Data_BuddyPokemon? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _result = source._result
      _updatedBuddy = source._updatedBuddy
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularEnumField(value: &_storage._result)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._updatedBuddy)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._result != .unest {
        try visitor.visitSingularEnumField(value: _storage._result, fieldNumber: 1)
      }
      if let v = _storage._updatedBuddy {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Networking_Responses_SetBuddyPokemonResponse, rhs: POGOProtos_Networking_Responses_SetBuddyPokemonResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._result != rhs_storage._result {return false}
        if _storage._updatedBuddy != rhs_storage._updatedBuddy {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension POGOProtos_Networking_Responses_SetBuddyPokemonResponse.Result: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNEST"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "ERROR_POKEMON_DEPLOYED"),
    3: .same(proto: "ERROR_POKEMON_NOT_OWNED"),
    4: .same(proto: "ERROR_POKEMON_IS_EGG"),
    5: .same(proto: "ERROR_INVALID_POKEMON"),
  ]
}
