## Base Image
FROM docker.pkg.github.com/realdevicemap/realdevicemap/realdevicemap:base

## Copy Files
COPY .build/debug/RealDeviceMap /app/
COPY resources /app/resources
COPY .gitsha /app/.gitsha
COPY .gitref /app/.gitref
RUN cd /app && wget https://raw.githubusercontent.com/apple/swift/master/utils/symbolicate-linux-fatal && chmod +x symbolicate-linux-fatal
COPY run-debug-docker /app/run-debug-docker
RUN cd /app && chmod +x run-debug-docker && chmod +x RealDeviceMap
CMD ["/app/run-debug-docker"]
