## Base Image
FROM docker.pkg.github.com/realdevicemap/realdevicemap/realdevicemap:base

## Copy Files
COPY .build/release/RealDeviceMap /app/
COPY resources /app/resources
RUN cd /app && chmod +x RealDeviceMap
CMD cd /app/ && ./RealDeviceMap
