## Base Image
FROM ubuntu:16.04

## Install Requirements

RUN apt-get -qq update

# Install swift run-time and build dependencies
RUN apt-get -qq -y install lsb-release curl git cmake ninja-build clang python uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config wget

# Install swiftenv
ENV SWIFTENV_ROOT /usr/local
ADD https://github.com/kylef/swiftenv/archive/1.2.0.tar.gz /tmp/swiftenv.tar.gz
RUN tar -xzf /tmp/swiftenv.tar.gz -C /usr/local/ --strip 1

# Add swiftenv shims to PATH
ENV PATH /usr/local/shims:$PATH

# Install swift 4.1
RUN swiftenv install 4.1
RUN touch /etc/ld.so.conf.d/swift.conf && echo "/usr/local/versions/4.1/usr/lib/swift/linux" >> /etc/ld.so.conf.d/swift.conf && ldconfig

# Install OpenSSL 1.1.1c
RUN apt-get -y update && apt-get install -y build-essential checkinstall zlib1g-dev
RUN cd /usr/local/src/ && wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz && tar -xf openssl-1.1.1c.tar.gz && cd openssl-1.1.1c && ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib && make && make test && make install && cd .. && rm -rf openssl-1.1.1c openssl-1.1.1c.tar.gz
RUN touch /etc/ld.so.conf.d/openssl-1.1.1c.conf && echo "/usr/local/ssl/lib" >> /etc/ld.so.conf.d/openssl-1.1.1c.conf && ldconfig

# Perfect-libcurl
RUN apt-get -y update && apt-get install -y libcurl4-openssl-dev

# Perfect-mysqlclient-Linux
RUN apt-get -y update && apt-get install -y libmysqlclient-dev && sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc

# Perfect-LinuxBridge
RUN apt-get -y update && apt-get install -y uuid-dev && rm -rf /var/lib/apt/lists/*

# ImageMagick for creating raid images
RUN apt-get -y update && apt-get install -y imagemagick && cp /usr/bin/convert /usr/local/bin

# MySQL Client
RUN apt-get -y update && apt-get install -y mysql-client-5.7
