// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Enums/Filter.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum POGOProtos_Enums_Filter: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unsetFilter // = 0
  case all // = 1
  case `default` // = 2
  case owned // = 3
  case featured // = 4
  case purchasable // = 5
  case unlockable // = 6
  case UNRECOGNIZED(Int)

  init() {
    self = .unsetFilter
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unsetFilter
    case 1: self = .all
    case 2: self = .default
    case 3: self = .owned
    case 4: self = .featured
    case 5: self = .purchasable
    case 6: self = .unlockable
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unsetFilter: return 0
    case .all: return 1
    case .default: return 2
    case .owned: return 3
    case .featured: return 4
    case .purchasable: return 5
    case .unlockable: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension POGOProtos_Enums_Filter: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Enums_Filter] = [
    .unsetFilter,
    .all,
    .default,
    .owned,
    .featured,
    .purchasable,
    .unlockable,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension POGOProtos_Enums_Filter: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSET_FILTER"),
    1: .same(proto: "ALL"),
    2: .same(proto: "DEFAULT"),
    3: .same(proto: "OWNED"),
    4: .same(proto: "FEATURED"),
    5: .same(proto: "PURCHASABLE"),
    6: .same(proto: "UNLOCKABLE"),
  ]
}
