// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Enums/PokemonFamilyId.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum POGOProtos_Enums_PokemonFamilyId: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case familyUnset // = 0
  case familyBulbasaur // = 1
  case familyCharmander // = 4
  case familySquirtle // = 7
  case familyCaterpie // = 10
  case familyWeedle // = 13
  case familyPidgey // = 16
  case familyRattata // = 19
  case familySpearow // = 21
  case familyEkans // = 23
  case familyPikachu // = 25
  case familySandshrew // = 27
  case familyNidoranFemale // = 29
  case familyNidoranMale // = 32
  case familyClefairy // = 35
  case familyVulpix // = 37
  case familyJigglypuff // = 39
  case familyZubat // = 41
  case familyOddish // = 43
  case familyParas // = 46
  case familyVenonat // = 48
  case familyDiglett // = 50
  case familyMeowth // = 52
  case familyPsyduck // = 54
  case familyMankey // = 56
  case familyGrowlithe // = 58
  case familyPoliwag // = 60
  case familyAbra // = 63
  case familyMachop // = 66
  case familyBellsprout // = 69
  case familyTentacool // = 72
  case familyGeodude // = 74
  case familyPonyta // = 77
  case familySlowpoke // = 79
  case familyMagnemite // = 81
  case familyFarfetchd // = 83
  case familyDoduo // = 84
  case familySeel // = 86
  case familyGrimer // = 88
  case familyShellder // = 90
  case familyGastly // = 92
  case familyOnix // = 95
  case familyDrowzee // = 96
  case familyHypno // = 97
  case familyKrabby // = 98
  case familyVoltorb // = 100
  case familyExeggcute // = 102
  case familyCubone // = 104
  case familyHitmonlee // = 106
  case familyHitmonchan // = 107
  case familyLickitung // = 108
  case familyKoffing // = 109
  case familyRhyhorn // = 111
  case familyChansey // = 113
  case familyTangela // = 114
  case familyKangaskhan // = 115
  case familyHorsea // = 116
  case familyGoldeen // = 118
  case familyStaryu // = 120
  case familyMrMime // = 122
  case familyScyther // = 123
  case familyJynx // = 124
  case familyElectabuzz // = 125
  case familyMagmar // = 126
  case familyPinsir // = 127
  case familyTauros // = 128
  case familyMagikarp // = 129
  case familyLapras // = 131
  case familyDitto // = 132
  case familyEevee // = 133
  case familyPorygon // = 137
  case familyOmanyte // = 138
  case familyKabuto // = 140
  case familyAerodactyl // = 142
  case familySnorlax // = 143
  case familyArticuno // = 144
  case familyZapdos // = 145
  case familyMoltres // = 146
  case familyDratini // = 147
  case familyMewtwo // = 150
  case familyMew // = 151
  case familyChikorita // = 152
  case familyCyndaquil // = 155
  case familyTotodile // = 158
  case familySentret // = 161
  case familyHoothoot // = 163
  case familyLedyba // = 165
  case familySpinarak // = 167
  case familyChinchou // = 170
  case familyTogepi // = 175
  case familyNatu // = 177
  case familyMareep // = 179
  case familyMarill // = 183
  case familySudowoodo // = 185
  case familyHoppip // = 187
  case familyAipom // = 190
  case familySunkern // = 191
  case familyYanma // = 193
  case familyWooper // = 194
  case familyMurkrow // = 198
  case familyMisdreavus // = 200
  case familyUnown // = 201
  case familyWobbuffet // = 202
  case familyGirafarig // = 203
  case familyPineco // = 204
  case familyDunsparce // = 206
  case familyGligar // = 207
  case familySnubbull // = 209
  case familyQwilfish // = 211
  case familyShuckle // = 213
  case familyHeracross // = 214
  case familySneasel // = 215
  case familyTeddiursa // = 216
  case familySlugma // = 218
  case familySwinub // = 220
  case familyCorsola // = 222
  case familyRemoraid // = 223
  case familyDelibird // = 225
  case familyMantine // = 226
  case familySkarmory // = 227
  case familyHoundour // = 228
  case familyPhanpy // = 231
  case familyStantler // = 234
  case familySmeargle // = 235
  case familyTyrogue // = 236
  case familyMiltank // = 241
  case familyRaikou // = 243
  case familyEntei // = 244
  case familySuicune // = 245
  case familyLarvitar // = 246
  case familyLugia // = 249
  case familyHoOh // = 250
  case familyCelebi // = 251
  case familyTreecko // = 252
  case familyTorchic // = 255
  case familyMudkip // = 258
  case familyPoochyena // = 261
  case familyZigzagoon // = 263
  case familyWurmple // = 265
  case familyLotad // = 270
  case familySeedot // = 273
  case familyTaillow // = 276
  case familyWingull // = 278
  case familyRalts // = 280
  case familySurskit // = 283
  case familyShroomish // = 285
  case familySlakoth // = 287
  case familyNincada // = 290
  case familyWhismur // = 293
  case familyMakuhita // = 296
  case familyNosepass // = 299
  case familySkitty // = 300
  case familySableye // = 302
  case familyMawile // = 303
  case familyAron // = 304
  case familyMeditite // = 307
  case familyElectrike // = 309
  case familyPlusle // = 311
  case familyMinun // = 312
  case familyVolbeat // = 313
  case familyIllumise // = 314
  case familyRoselia // = 315
  case familyGulpin // = 316
  case familyCarvanha // = 318
  case familyWailmer // = 320
  case familyNumel // = 322
  case familyTorkoal // = 324
  case familySpoink // = 325
  case familySpinda // = 327
  case familyTrapinch // = 328
  case familyCacnea // = 331
  case familySwablu // = 333
  case familyZangoose // = 335
  case familySeviper // = 336
  case familyLunatone // = 337
  case familySolrock // = 338
  case familyBarboach // = 339
  case familyCorphish // = 341
  case familyBaltoy // = 343
  case familyLileep // = 345
  case familyAnorith // = 347
  case familyFeebas // = 349
  case familyCastform // = 351
  case familyKecleon // = 352
  case familyShuppet // = 353
  case familyDuskull // = 355
  case familyTropius // = 357
  case familyChimecho // = 358
  case familyAbsol // = 359
  case familySnorunt // = 361
  case familySpheal // = 363
  case familyClamperl // = 366
  case familyRelicanth // = 369
  case familyLuvdisc // = 370
  case familyBagon // = 371
  case familyBeldum // = 374
  case familyRegirock // = 377
  case familyRegice // = 378
  case familyRegisteel // = 379
  case familyLatias // = 380
  case familyLatios // = 381
  case familyKyogre // = 382
  case familyGroudon // = 383
  case familyRayquaza // = 384
  case familyJirachi // = 385
  case familyDeoxys // = 386
  case UNRECOGNIZED(Int)

  init() {
    self = .familyUnset
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .familyUnset
    case 1: self = .familyBulbasaur
    case 4: self = .familyCharmander
    case 7: self = .familySquirtle
    case 10: self = .familyCaterpie
    case 13: self = .familyWeedle
    case 16: self = .familyPidgey
    case 19: self = .familyRattata
    case 21: self = .familySpearow
    case 23: self = .familyEkans
    case 25: self = .familyPikachu
    case 27: self = .familySandshrew
    case 29: self = .familyNidoranFemale
    case 32: self = .familyNidoranMale
    case 35: self = .familyClefairy
    case 37: self = .familyVulpix
    case 39: self = .familyJigglypuff
    case 41: self = .familyZubat
    case 43: self = .familyOddish
    case 46: self = .familyParas
    case 48: self = .familyVenonat
    case 50: self = .familyDiglett
    case 52: self = .familyMeowth
    case 54: self = .familyPsyduck
    case 56: self = .familyMankey
    case 58: self = .familyGrowlithe
    case 60: self = .familyPoliwag
    case 63: self = .familyAbra
    case 66: self = .familyMachop
    case 69: self = .familyBellsprout
    case 72: self = .familyTentacool
    case 74: self = .familyGeodude
    case 77: self = .familyPonyta
    case 79: self = .familySlowpoke
    case 81: self = .familyMagnemite
    case 83: self = .familyFarfetchd
    case 84: self = .familyDoduo
    case 86: self = .familySeel
    case 88: self = .familyGrimer
    case 90: self = .familyShellder
    case 92: self = .familyGastly
    case 95: self = .familyOnix
    case 96: self = .familyDrowzee
    case 97: self = .familyHypno
    case 98: self = .familyKrabby
    case 100: self = .familyVoltorb
    case 102: self = .familyExeggcute
    case 104: self = .familyCubone
    case 106: self = .familyHitmonlee
    case 107: self = .familyHitmonchan
    case 108: self = .familyLickitung
    case 109: self = .familyKoffing
    case 111: self = .familyRhyhorn
    case 113: self = .familyChansey
    case 114: self = .familyTangela
    case 115: self = .familyKangaskhan
    case 116: self = .familyHorsea
    case 118: self = .familyGoldeen
    case 120: self = .familyStaryu
    case 122: self = .familyMrMime
    case 123: self = .familyScyther
    case 124: self = .familyJynx
    case 125: self = .familyElectabuzz
    case 126: self = .familyMagmar
    case 127: self = .familyPinsir
    case 128: self = .familyTauros
    case 129: self = .familyMagikarp
    case 131: self = .familyLapras
    case 132: self = .familyDitto
    case 133: self = .familyEevee
    case 137: self = .familyPorygon
    case 138: self = .familyOmanyte
    case 140: self = .familyKabuto
    case 142: self = .familyAerodactyl
    case 143: self = .familySnorlax
    case 144: self = .familyArticuno
    case 145: self = .familyZapdos
    case 146: self = .familyMoltres
    case 147: self = .familyDratini
    case 150: self = .familyMewtwo
    case 151: self = .familyMew
    case 152: self = .familyChikorita
    case 155: self = .familyCyndaquil
    case 158: self = .familyTotodile
    case 161: self = .familySentret
    case 163: self = .familyHoothoot
    case 165: self = .familyLedyba
    case 167: self = .familySpinarak
    case 170: self = .familyChinchou
    case 175: self = .familyTogepi
    case 177: self = .familyNatu
    case 179: self = .familyMareep
    case 183: self = .familyMarill
    case 185: self = .familySudowoodo
    case 187: self = .familyHoppip
    case 190: self = .familyAipom
    case 191: self = .familySunkern
    case 193: self = .familyYanma
    case 194: self = .familyWooper
    case 198: self = .familyMurkrow
    case 200: self = .familyMisdreavus
    case 201: self = .familyUnown
    case 202: self = .familyWobbuffet
    case 203: self = .familyGirafarig
    case 204: self = .familyPineco
    case 206: self = .familyDunsparce
    case 207: self = .familyGligar
    case 209: self = .familySnubbull
    case 211: self = .familyQwilfish
    case 213: self = .familyShuckle
    case 214: self = .familyHeracross
    case 215: self = .familySneasel
    case 216: self = .familyTeddiursa
    case 218: self = .familySlugma
    case 220: self = .familySwinub
    case 222: self = .familyCorsola
    case 223: self = .familyRemoraid
    case 225: self = .familyDelibird
    case 226: self = .familyMantine
    case 227: self = .familySkarmory
    case 228: self = .familyHoundour
    case 231: self = .familyPhanpy
    case 234: self = .familyStantler
    case 235: self = .familySmeargle
    case 236: self = .familyTyrogue
    case 241: self = .familyMiltank
    case 243: self = .familyRaikou
    case 244: self = .familyEntei
    case 245: self = .familySuicune
    case 246: self = .familyLarvitar
    case 249: self = .familyLugia
    case 250: self = .familyHoOh
    case 251: self = .familyCelebi
    case 252: self = .familyTreecko
    case 255: self = .familyTorchic
    case 258: self = .familyMudkip
    case 261: self = .familyPoochyena
    case 263: self = .familyZigzagoon
    case 265: self = .familyWurmple
    case 270: self = .familyLotad
    case 273: self = .familySeedot
    case 276: self = .familyTaillow
    case 278: self = .familyWingull
    case 280: self = .familyRalts
    case 283: self = .familySurskit
    case 285: self = .familyShroomish
    case 287: self = .familySlakoth
    case 290: self = .familyNincada
    case 293: self = .familyWhismur
    case 296: self = .familyMakuhita
    case 299: self = .familyNosepass
    case 300: self = .familySkitty
    case 302: self = .familySableye
    case 303: self = .familyMawile
    case 304: self = .familyAron
    case 307: self = .familyMeditite
    case 309: self = .familyElectrike
    case 311: self = .familyPlusle
    case 312: self = .familyMinun
    case 313: self = .familyVolbeat
    case 314: self = .familyIllumise
    case 315: self = .familyRoselia
    case 316: self = .familyGulpin
    case 318: self = .familyCarvanha
    case 320: self = .familyWailmer
    case 322: self = .familyNumel
    case 324: self = .familyTorkoal
    case 325: self = .familySpoink
    case 327: self = .familySpinda
    case 328: self = .familyTrapinch
    case 331: self = .familyCacnea
    case 333: self = .familySwablu
    case 335: self = .familyZangoose
    case 336: self = .familySeviper
    case 337: self = .familyLunatone
    case 338: self = .familySolrock
    case 339: self = .familyBarboach
    case 341: self = .familyCorphish
    case 343: self = .familyBaltoy
    case 345: self = .familyLileep
    case 347: self = .familyAnorith
    case 349: self = .familyFeebas
    case 351: self = .familyCastform
    case 352: self = .familyKecleon
    case 353: self = .familyShuppet
    case 355: self = .familyDuskull
    case 357: self = .familyTropius
    case 358: self = .familyChimecho
    case 359: self = .familyAbsol
    case 361: self = .familySnorunt
    case 363: self = .familySpheal
    case 366: self = .familyClamperl
    case 369: self = .familyRelicanth
    case 370: self = .familyLuvdisc
    case 371: self = .familyBagon
    case 374: self = .familyBeldum
    case 377: self = .familyRegirock
    case 378: self = .familyRegice
    case 379: self = .familyRegisteel
    case 380: self = .familyLatias
    case 381: self = .familyLatios
    case 382: self = .familyKyogre
    case 383: self = .familyGroudon
    case 384: self = .familyRayquaza
    case 385: self = .familyJirachi
    case 386: self = .familyDeoxys
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .familyUnset: return 0
    case .familyBulbasaur: return 1
    case .familyCharmander: return 4
    case .familySquirtle: return 7
    case .familyCaterpie: return 10
    case .familyWeedle: return 13
    case .familyPidgey: return 16
    case .familyRattata: return 19
    case .familySpearow: return 21
    case .familyEkans: return 23
    case .familyPikachu: return 25
    case .familySandshrew: return 27
    case .familyNidoranFemale: return 29
    case .familyNidoranMale: return 32
    case .familyClefairy: return 35
    case .familyVulpix: return 37
    case .familyJigglypuff: return 39
    case .familyZubat: return 41
    case .familyOddish: return 43
    case .familyParas: return 46
    case .familyVenonat: return 48
    case .familyDiglett: return 50
    case .familyMeowth: return 52
    case .familyPsyduck: return 54
    case .familyMankey: return 56
    case .familyGrowlithe: return 58
    case .familyPoliwag: return 60
    case .familyAbra: return 63
    case .familyMachop: return 66
    case .familyBellsprout: return 69
    case .familyTentacool: return 72
    case .familyGeodude: return 74
    case .familyPonyta: return 77
    case .familySlowpoke: return 79
    case .familyMagnemite: return 81
    case .familyFarfetchd: return 83
    case .familyDoduo: return 84
    case .familySeel: return 86
    case .familyGrimer: return 88
    case .familyShellder: return 90
    case .familyGastly: return 92
    case .familyOnix: return 95
    case .familyDrowzee: return 96
    case .familyHypno: return 97
    case .familyKrabby: return 98
    case .familyVoltorb: return 100
    case .familyExeggcute: return 102
    case .familyCubone: return 104
    case .familyHitmonlee: return 106
    case .familyHitmonchan: return 107
    case .familyLickitung: return 108
    case .familyKoffing: return 109
    case .familyRhyhorn: return 111
    case .familyChansey: return 113
    case .familyTangela: return 114
    case .familyKangaskhan: return 115
    case .familyHorsea: return 116
    case .familyGoldeen: return 118
    case .familyStaryu: return 120
    case .familyMrMime: return 122
    case .familyScyther: return 123
    case .familyJynx: return 124
    case .familyElectabuzz: return 125
    case .familyMagmar: return 126
    case .familyPinsir: return 127
    case .familyTauros: return 128
    case .familyMagikarp: return 129
    case .familyLapras: return 131
    case .familyDitto: return 132
    case .familyEevee: return 133
    case .familyPorygon: return 137
    case .familyOmanyte: return 138
    case .familyKabuto: return 140
    case .familyAerodactyl: return 142
    case .familySnorlax: return 143
    case .familyArticuno: return 144
    case .familyZapdos: return 145
    case .familyMoltres: return 146
    case .familyDratini: return 147
    case .familyMewtwo: return 150
    case .familyMew: return 151
    case .familyChikorita: return 152
    case .familyCyndaquil: return 155
    case .familyTotodile: return 158
    case .familySentret: return 161
    case .familyHoothoot: return 163
    case .familyLedyba: return 165
    case .familySpinarak: return 167
    case .familyChinchou: return 170
    case .familyTogepi: return 175
    case .familyNatu: return 177
    case .familyMareep: return 179
    case .familyMarill: return 183
    case .familySudowoodo: return 185
    case .familyHoppip: return 187
    case .familyAipom: return 190
    case .familySunkern: return 191
    case .familyYanma: return 193
    case .familyWooper: return 194
    case .familyMurkrow: return 198
    case .familyMisdreavus: return 200
    case .familyUnown: return 201
    case .familyWobbuffet: return 202
    case .familyGirafarig: return 203
    case .familyPineco: return 204
    case .familyDunsparce: return 206
    case .familyGligar: return 207
    case .familySnubbull: return 209
    case .familyQwilfish: return 211
    case .familyShuckle: return 213
    case .familyHeracross: return 214
    case .familySneasel: return 215
    case .familyTeddiursa: return 216
    case .familySlugma: return 218
    case .familySwinub: return 220
    case .familyCorsola: return 222
    case .familyRemoraid: return 223
    case .familyDelibird: return 225
    case .familyMantine: return 226
    case .familySkarmory: return 227
    case .familyHoundour: return 228
    case .familyPhanpy: return 231
    case .familyStantler: return 234
    case .familySmeargle: return 235
    case .familyTyrogue: return 236
    case .familyMiltank: return 241
    case .familyRaikou: return 243
    case .familyEntei: return 244
    case .familySuicune: return 245
    case .familyLarvitar: return 246
    case .familyLugia: return 249
    case .familyHoOh: return 250
    case .familyCelebi: return 251
    case .familyTreecko: return 252
    case .familyTorchic: return 255
    case .familyMudkip: return 258
    case .familyPoochyena: return 261
    case .familyZigzagoon: return 263
    case .familyWurmple: return 265
    case .familyLotad: return 270
    case .familySeedot: return 273
    case .familyTaillow: return 276
    case .familyWingull: return 278
    case .familyRalts: return 280
    case .familySurskit: return 283
    case .familyShroomish: return 285
    case .familySlakoth: return 287
    case .familyNincada: return 290
    case .familyWhismur: return 293
    case .familyMakuhita: return 296
    case .familyNosepass: return 299
    case .familySkitty: return 300
    case .familySableye: return 302
    case .familyMawile: return 303
    case .familyAron: return 304
    case .familyMeditite: return 307
    case .familyElectrike: return 309
    case .familyPlusle: return 311
    case .familyMinun: return 312
    case .familyVolbeat: return 313
    case .familyIllumise: return 314
    case .familyRoselia: return 315
    case .familyGulpin: return 316
    case .familyCarvanha: return 318
    case .familyWailmer: return 320
    case .familyNumel: return 322
    case .familyTorkoal: return 324
    case .familySpoink: return 325
    case .familySpinda: return 327
    case .familyTrapinch: return 328
    case .familyCacnea: return 331
    case .familySwablu: return 333
    case .familyZangoose: return 335
    case .familySeviper: return 336
    case .familyLunatone: return 337
    case .familySolrock: return 338
    case .familyBarboach: return 339
    case .familyCorphish: return 341
    case .familyBaltoy: return 343
    case .familyLileep: return 345
    case .familyAnorith: return 347
    case .familyFeebas: return 349
    case .familyCastform: return 351
    case .familyKecleon: return 352
    case .familyShuppet: return 353
    case .familyDuskull: return 355
    case .familyTropius: return 357
    case .familyChimecho: return 358
    case .familyAbsol: return 359
    case .familySnorunt: return 361
    case .familySpheal: return 363
    case .familyClamperl: return 366
    case .familyRelicanth: return 369
    case .familyLuvdisc: return 370
    case .familyBagon: return 371
    case .familyBeldum: return 374
    case .familyRegirock: return 377
    case .familyRegice: return 378
    case .familyRegisteel: return 379
    case .familyLatias: return 380
    case .familyLatios: return 381
    case .familyKyogre: return 382
    case .familyGroudon: return 383
    case .familyRayquaza: return 384
    case .familyJirachi: return 385
    case .familyDeoxys: return 386
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension POGOProtos_Enums_PokemonFamilyId: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Enums_PokemonFamilyId] = [
    .familyUnset,
    .familyBulbasaur,
    .familyCharmander,
    .familySquirtle,
    .familyCaterpie,
    .familyWeedle,
    .familyPidgey,
    .familyRattata,
    .familySpearow,
    .familyEkans,
    .familyPikachu,
    .familySandshrew,
    .familyNidoranFemale,
    .familyNidoranMale,
    .familyClefairy,
    .familyVulpix,
    .familyJigglypuff,
    .familyZubat,
    .familyOddish,
    .familyParas,
    .familyVenonat,
    .familyDiglett,
    .familyMeowth,
    .familyPsyduck,
    .familyMankey,
    .familyGrowlithe,
    .familyPoliwag,
    .familyAbra,
    .familyMachop,
    .familyBellsprout,
    .familyTentacool,
    .familyGeodude,
    .familyPonyta,
    .familySlowpoke,
    .familyMagnemite,
    .familyFarfetchd,
    .familyDoduo,
    .familySeel,
    .familyGrimer,
    .familyShellder,
    .familyGastly,
    .familyOnix,
    .familyDrowzee,
    .familyHypno,
    .familyKrabby,
    .familyVoltorb,
    .familyExeggcute,
    .familyCubone,
    .familyHitmonlee,
    .familyHitmonchan,
    .familyLickitung,
    .familyKoffing,
    .familyRhyhorn,
    .familyChansey,
    .familyTangela,
    .familyKangaskhan,
    .familyHorsea,
    .familyGoldeen,
    .familyStaryu,
    .familyMrMime,
    .familyScyther,
    .familyJynx,
    .familyElectabuzz,
    .familyMagmar,
    .familyPinsir,
    .familyTauros,
    .familyMagikarp,
    .familyLapras,
    .familyDitto,
    .familyEevee,
    .familyPorygon,
    .familyOmanyte,
    .familyKabuto,
    .familyAerodactyl,
    .familySnorlax,
    .familyArticuno,
    .familyZapdos,
    .familyMoltres,
    .familyDratini,
    .familyMewtwo,
    .familyMew,
    .familyChikorita,
    .familyCyndaquil,
    .familyTotodile,
    .familySentret,
    .familyHoothoot,
    .familyLedyba,
    .familySpinarak,
    .familyChinchou,
    .familyTogepi,
    .familyNatu,
    .familyMareep,
    .familyMarill,
    .familySudowoodo,
    .familyHoppip,
    .familyAipom,
    .familySunkern,
    .familyYanma,
    .familyWooper,
    .familyMurkrow,
    .familyMisdreavus,
    .familyUnown,
    .familyWobbuffet,
    .familyGirafarig,
    .familyPineco,
    .familyDunsparce,
    .familyGligar,
    .familySnubbull,
    .familyQwilfish,
    .familyShuckle,
    .familyHeracross,
    .familySneasel,
    .familyTeddiursa,
    .familySlugma,
    .familySwinub,
    .familyCorsola,
    .familyRemoraid,
    .familyDelibird,
    .familyMantine,
    .familySkarmory,
    .familyHoundour,
    .familyPhanpy,
    .familyStantler,
    .familySmeargle,
    .familyTyrogue,
    .familyMiltank,
    .familyRaikou,
    .familyEntei,
    .familySuicune,
    .familyLarvitar,
    .familyLugia,
    .familyHoOh,
    .familyCelebi,
    .familyTreecko,
    .familyTorchic,
    .familyMudkip,
    .familyPoochyena,
    .familyZigzagoon,
    .familyWurmple,
    .familyLotad,
    .familySeedot,
    .familyTaillow,
    .familyWingull,
    .familyRalts,
    .familySurskit,
    .familyShroomish,
    .familySlakoth,
    .familyNincada,
    .familyWhismur,
    .familyMakuhita,
    .familyNosepass,
    .familySkitty,
    .familySableye,
    .familyMawile,
    .familyAron,
    .familyMeditite,
    .familyElectrike,
    .familyPlusle,
    .familyMinun,
    .familyVolbeat,
    .familyIllumise,
    .familyRoselia,
    .familyGulpin,
    .familyCarvanha,
    .familyWailmer,
    .familyNumel,
    .familyTorkoal,
    .familySpoink,
    .familySpinda,
    .familyTrapinch,
    .familyCacnea,
    .familySwablu,
    .familyZangoose,
    .familySeviper,
    .familyLunatone,
    .familySolrock,
    .familyBarboach,
    .familyCorphish,
    .familyBaltoy,
    .familyLileep,
    .familyAnorith,
    .familyFeebas,
    .familyCastform,
    .familyKecleon,
    .familyShuppet,
    .familyDuskull,
    .familyTropius,
    .familyChimecho,
    .familyAbsol,
    .familySnorunt,
    .familySpheal,
    .familyClamperl,
    .familyRelicanth,
    .familyLuvdisc,
    .familyBagon,
    .familyBeldum,
    .familyRegirock,
    .familyRegice,
    .familyRegisteel,
    .familyLatias,
    .familyLatios,
    .familyKyogre,
    .familyGroudon,
    .familyRayquaza,
    .familyJirachi,
    .familyDeoxys,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension POGOProtos_Enums_PokemonFamilyId: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "FAMILY_UNSET"),
    1: .same(proto: "FAMILY_BULBASAUR"),
    4: .same(proto: "FAMILY_CHARMANDER"),
    7: .same(proto: "FAMILY_SQUIRTLE"),
    10: .same(proto: "FAMILY_CATERPIE"),
    13: .same(proto: "FAMILY_WEEDLE"),
    16: .same(proto: "FAMILY_PIDGEY"),
    19: .same(proto: "FAMILY_RATTATA"),
    21: .same(proto: "FAMILY_SPEAROW"),
    23: .same(proto: "FAMILY_EKANS"),
    25: .same(proto: "FAMILY_PIKACHU"),
    27: .same(proto: "FAMILY_SANDSHREW"),
    29: .same(proto: "FAMILY_NIDORAN_FEMALE"),
    32: .same(proto: "FAMILY_NIDORAN_MALE"),
    35: .same(proto: "FAMILY_CLEFAIRY"),
    37: .same(proto: "FAMILY_VULPIX"),
    39: .same(proto: "FAMILY_JIGGLYPUFF"),
    41: .same(proto: "FAMILY_ZUBAT"),
    43: .same(proto: "FAMILY_ODDISH"),
    46: .same(proto: "FAMILY_PARAS"),
    48: .same(proto: "FAMILY_VENONAT"),
    50: .same(proto: "FAMILY_DIGLETT"),
    52: .same(proto: "FAMILY_MEOWTH"),
    54: .same(proto: "FAMILY_PSYDUCK"),
    56: .same(proto: "FAMILY_MANKEY"),
    58: .same(proto: "FAMILY_GROWLITHE"),
    60: .same(proto: "FAMILY_POLIWAG"),
    63: .same(proto: "FAMILY_ABRA"),
    66: .same(proto: "FAMILY_MACHOP"),
    69: .same(proto: "FAMILY_BELLSPROUT"),
    72: .same(proto: "FAMILY_TENTACOOL"),
    74: .same(proto: "FAMILY_GEODUDE"),
    77: .same(proto: "FAMILY_PONYTA"),
    79: .same(proto: "FAMILY_SLOWPOKE"),
    81: .same(proto: "FAMILY_MAGNEMITE"),
    83: .same(proto: "FAMILY_FARFETCHD"),
    84: .same(proto: "FAMILY_DODUO"),
    86: .same(proto: "FAMILY_SEEL"),
    88: .same(proto: "FAMILY_GRIMER"),
    90: .same(proto: "FAMILY_SHELLDER"),
    92: .same(proto: "FAMILY_GASTLY"),
    95: .same(proto: "FAMILY_ONIX"),
    96: .same(proto: "FAMILY_DROWZEE"),
    97: .same(proto: "FAMILY_HYPNO"),
    98: .same(proto: "FAMILY_KRABBY"),
    100: .same(proto: "FAMILY_VOLTORB"),
    102: .same(proto: "FAMILY_EXEGGCUTE"),
    104: .same(proto: "FAMILY_CUBONE"),
    106: .same(proto: "FAMILY_HITMONLEE"),
    107: .same(proto: "FAMILY_HITMONCHAN"),
    108: .same(proto: "FAMILY_LICKITUNG"),
    109: .same(proto: "FAMILY_KOFFING"),
    111: .same(proto: "FAMILY_RHYHORN"),
    113: .same(proto: "FAMILY_CHANSEY"),
    114: .same(proto: "FAMILY_TANGELA"),
    115: .same(proto: "FAMILY_KANGASKHAN"),
    116: .same(proto: "FAMILY_HORSEA"),
    118: .same(proto: "FAMILY_GOLDEEN"),
    120: .same(proto: "FAMILY_STARYU"),
    122: .same(proto: "FAMILY_MR_MIME"),
    123: .same(proto: "FAMILY_SCYTHER"),
    124: .same(proto: "FAMILY_JYNX"),
    125: .same(proto: "FAMILY_ELECTABUZZ"),
    126: .same(proto: "FAMILY_MAGMAR"),
    127: .same(proto: "FAMILY_PINSIR"),
    128: .same(proto: "FAMILY_TAUROS"),
    129: .same(proto: "FAMILY_MAGIKARP"),
    131: .same(proto: "FAMILY_LAPRAS"),
    132: .same(proto: "FAMILY_DITTO"),
    133: .same(proto: "FAMILY_EEVEE"),
    137: .same(proto: "FAMILY_PORYGON"),
    138: .same(proto: "FAMILY_OMANYTE"),
    140: .same(proto: "FAMILY_KABUTO"),
    142: .same(proto: "FAMILY_AERODACTYL"),
    143: .same(proto: "FAMILY_SNORLAX"),
    144: .same(proto: "FAMILY_ARTICUNO"),
    145: .same(proto: "FAMILY_ZAPDOS"),
    146: .same(proto: "FAMILY_MOLTRES"),
    147: .same(proto: "FAMILY_DRATINI"),
    150: .same(proto: "FAMILY_MEWTWO"),
    151: .same(proto: "FAMILY_MEW"),
    152: .same(proto: "FAMILY_CHIKORITA"),
    155: .same(proto: "FAMILY_CYNDAQUIL"),
    158: .same(proto: "FAMILY_TOTODILE"),
    161: .same(proto: "FAMILY_SENTRET"),
    163: .same(proto: "FAMILY_HOOTHOOT"),
    165: .same(proto: "FAMILY_LEDYBA"),
    167: .same(proto: "FAMILY_SPINARAK"),
    170: .same(proto: "FAMILY_CHINCHOU"),
    175: .same(proto: "FAMILY_TOGEPI"),
    177: .same(proto: "FAMILY_NATU"),
    179: .same(proto: "FAMILY_MAREEP"),
    183: .same(proto: "FAMILY_MARILL"),
    185: .same(proto: "FAMILY_SUDOWOODO"),
    187: .same(proto: "FAMILY_HOPPIP"),
    190: .same(proto: "FAMILY_AIPOM"),
    191: .same(proto: "FAMILY_SUNKERN"),
    193: .same(proto: "FAMILY_YANMA"),
    194: .same(proto: "FAMILY_WOOPER"),
    198: .same(proto: "FAMILY_MURKROW"),
    200: .same(proto: "FAMILY_MISDREAVUS"),
    201: .same(proto: "FAMILY_UNOWN"),
    202: .same(proto: "FAMILY_WOBBUFFET"),
    203: .same(proto: "FAMILY_GIRAFARIG"),
    204: .same(proto: "FAMILY_PINECO"),
    206: .same(proto: "FAMILY_DUNSPARCE"),
    207: .same(proto: "FAMILY_GLIGAR"),
    209: .same(proto: "FAMILY_SNUBBULL"),
    211: .same(proto: "FAMILY_QWILFISH"),
    213: .same(proto: "FAMILY_SHUCKLE"),
    214: .same(proto: "FAMILY_HERACROSS"),
    215: .same(proto: "FAMILY_SNEASEL"),
    216: .same(proto: "FAMILY_TEDDIURSA"),
    218: .same(proto: "FAMILY_SLUGMA"),
    220: .same(proto: "FAMILY_SWINUB"),
    222: .same(proto: "FAMILY_CORSOLA"),
    223: .same(proto: "FAMILY_REMORAID"),
    225: .same(proto: "FAMILY_DELIBIRD"),
    226: .same(proto: "FAMILY_MANTINE"),
    227: .same(proto: "FAMILY_SKARMORY"),
    228: .same(proto: "FAMILY_HOUNDOUR"),
    231: .same(proto: "FAMILY_PHANPY"),
    234: .same(proto: "FAMILY_STANTLER"),
    235: .same(proto: "FAMILY_SMEARGLE"),
    236: .same(proto: "FAMILY_TYROGUE"),
    241: .same(proto: "FAMILY_MILTANK"),
    243: .same(proto: "FAMILY_RAIKOU"),
    244: .same(proto: "FAMILY_ENTEI"),
    245: .same(proto: "FAMILY_SUICUNE"),
    246: .same(proto: "FAMILY_LARVITAR"),
    249: .same(proto: "FAMILY_LUGIA"),
    250: .same(proto: "FAMILY_HO_OH"),
    251: .same(proto: "FAMILY_CELEBI"),
    252: .same(proto: "FAMILY_TREECKO"),
    255: .same(proto: "FAMILY_TORCHIC"),
    258: .same(proto: "FAMILY_MUDKIP"),
    261: .same(proto: "FAMILY_POOCHYENA"),
    263: .same(proto: "FAMILY_ZIGZAGOON"),
    265: .same(proto: "FAMILY_WURMPLE"),
    270: .same(proto: "FAMILY_LOTAD"),
    273: .same(proto: "FAMILY_SEEDOT"),
    276: .same(proto: "FAMILY_TAILLOW"),
    278: .same(proto: "FAMILY_WINGULL"),
    280: .same(proto: "FAMILY_RALTS"),
    283: .same(proto: "FAMILY_SURSKIT"),
    285: .same(proto: "FAMILY_SHROOMISH"),
    287: .same(proto: "FAMILY_SLAKOTH"),
    290: .same(proto: "FAMILY_NINCADA"),
    293: .same(proto: "FAMILY_WHISMUR"),
    296: .same(proto: "FAMILY_MAKUHITA"),
    299: .same(proto: "FAMILY_NOSEPASS"),
    300: .same(proto: "FAMILY_SKITTY"),
    302: .same(proto: "FAMILY_SABLEYE"),
    303: .same(proto: "FAMILY_MAWILE"),
    304: .same(proto: "FAMILY_ARON"),
    307: .same(proto: "FAMILY_MEDITITE"),
    309: .same(proto: "FAMILY_ELECTRIKE"),
    311: .same(proto: "FAMILY_PLUSLE"),
    312: .same(proto: "FAMILY_MINUN"),
    313: .same(proto: "FAMILY_VOLBEAT"),
    314: .same(proto: "FAMILY_ILLUMISE"),
    315: .same(proto: "FAMILY_ROSELIA"),
    316: .same(proto: "FAMILY_GULPIN"),
    318: .same(proto: "FAMILY_CARVANHA"),
    320: .same(proto: "FAMILY_WAILMER"),
    322: .same(proto: "FAMILY_NUMEL"),
    324: .same(proto: "FAMILY_TORKOAL"),
    325: .same(proto: "FAMILY_SPOINK"),
    327: .same(proto: "FAMILY_SPINDA"),
    328: .same(proto: "FAMILY_TRAPINCH"),
    331: .same(proto: "FAMILY_CACNEA"),
    333: .same(proto: "FAMILY_SWABLU"),
    335: .same(proto: "FAMILY_ZANGOOSE"),
    336: .same(proto: "FAMILY_SEVIPER"),
    337: .same(proto: "FAMILY_LUNATONE"),
    338: .same(proto: "FAMILY_SOLROCK"),
    339: .same(proto: "FAMILY_BARBOACH"),
    341: .same(proto: "FAMILY_CORPHISH"),
    343: .same(proto: "FAMILY_BALTOY"),
    345: .same(proto: "FAMILY_LILEEP"),
    347: .same(proto: "FAMILY_ANORITH"),
    349: .same(proto: "FAMILY_FEEBAS"),
    351: .same(proto: "FAMILY_CASTFORM"),
    352: .same(proto: "FAMILY_KECLEON"),
    353: .same(proto: "FAMILY_SHUPPET"),
    355: .same(proto: "FAMILY_DUSKULL"),
    357: .same(proto: "FAMILY_TROPIUS"),
    358: .same(proto: "FAMILY_CHIMECHO"),
    359: .same(proto: "FAMILY_ABSOL"),
    361: .same(proto: "FAMILY_SNORUNT"),
    363: .same(proto: "FAMILY_SPHEAL"),
    366: .same(proto: "FAMILY_CLAMPERL"),
    369: .same(proto: "FAMILY_RELICANTH"),
    370: .same(proto: "FAMILY_LUVDISC"),
    371: .same(proto: "FAMILY_BAGON"),
    374: .same(proto: "FAMILY_BELDUM"),
    377: .same(proto: "FAMILY_REGIROCK"),
    378: .same(proto: "FAMILY_REGICE"),
    379: .same(proto: "FAMILY_REGISTEEL"),
    380: .same(proto: "FAMILY_LATIAS"),
    381: .same(proto: "FAMILY_LATIOS"),
    382: .same(proto: "FAMILY_KYOGRE"),
    383: .same(proto: "FAMILY_GROUDON"),
    384: .same(proto: "FAMILY_RAYQUAZA"),
    385: .same(proto: "FAMILY_JIRACHI"),
    386: .same(proto: "FAMILY_DEOXYS"),
  ]
}
