// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Settings/Master/Item/BattleAttributes.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Settings_Master_Item_BattleAttributes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var staPercent: Float = 0

  var atkPercent: Float = 0

  var defPercent: Float = 0

  var durationS: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Settings.Master.Item"

extension POGOProtos_Settings_Master_Item_BattleAttributes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BattleAttributes"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "sta_percent"),
    2: .standard(proto: "atk_percent"),
    3: .standard(proto: "def_percent"),
    4: .standard(proto: "duration_s"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.staPercent)
      case 2: try decoder.decodeSingularFloatField(value: &self.atkPercent)
      case 3: try decoder.decodeSingularFloatField(value: &self.defPercent)
      case 4: try decoder.decodeSingularFloatField(value: &self.durationS)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.staPercent != 0 {
      try visitor.visitSingularFloatField(value: self.staPercent, fieldNumber: 1)
    }
    if self.atkPercent != 0 {
      try visitor.visitSingularFloatField(value: self.atkPercent, fieldNumber: 2)
    }
    if self.defPercent != 0 {
      try visitor.visitSingularFloatField(value: self.defPercent, fieldNumber: 3)
    }
    if self.durationS != 0 {
      try visitor.visitSingularFloatField(value: self.durationS, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Settings_Master_Item_BattleAttributes, rhs: POGOProtos_Settings_Master_Item_BattleAttributes) -> Bool {
    if lhs.staPercent != rhs.staPercent {return false}
    if lhs.atkPercent != rhs.atkPercent {return false}
    if lhs.defPercent != rhs.defPercent {return false}
    if lhs.durationS != rhs.durationS {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
