// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Data/Gym/GymStatusAndDefenders.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Data_Gym_GymStatusAndDefenders {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pokemonFortProto: POGOProtos_Map_Fort_FortData {
    get {return _storage._pokemonFortProto ?? POGOProtos_Map_Fort_FortData()}
    set {_uniqueStorage()._pokemonFortProto = newValue}
  }
  /// Returns true if `pokemonFortProto` has been explicitly set.
  var hasPokemonFortProto: Bool {return _storage._pokemonFortProto != nil}
  /// Clears the value of `pokemonFortProto`. Subsequent reads from it will return its default value.
  mutating func clearPokemonFortProto() {_uniqueStorage()._pokemonFortProto = nil}

  var gymDefender: [POGOProtos_Data_Gym_GymDefender] {
    get {return _storage._gymDefender}
    set {_uniqueStorage()._gymDefender = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Data.Gym"

extension POGOProtos_Data_Gym_GymStatusAndDefenders: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GymStatusAndDefenders"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "pokemon_fort_proto"),
    2: .standard(proto: "gym_defender"),
  ]

  fileprivate class _StorageClass {
    var _pokemonFortProto: POGOProtos_Map_Fort_FortData? = nil
    var _gymDefender: [POGOProtos_Data_Gym_GymDefender] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _pokemonFortProto = source._pokemonFortProto
      _gymDefender = source._gymDefender
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._pokemonFortProto)
        case 2: try decoder.decodeRepeatedMessageField(value: &_storage._gymDefender)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._pokemonFortProto {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._gymDefender.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._gymDefender, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Data_Gym_GymStatusAndDefenders, rhs: POGOProtos_Data_Gym_GymStatusAndDefenders) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._pokemonFortProto != rhs_storage._pokemonFortProto {return false}
        if _storage._gymDefender != rhs_storage._gymDefender {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
