// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Data/Battle/BattleActionType.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum POGOProtos_Data_Battle_BattleActionType: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case actionUnset // = 0
  case actionAttack // = 1
  case actionDodge // = 2
  case actionSpecialAttack // = 3
  case actionSwapPokemon // = 4
  case actionFaint // = 5
  case actionPlayerJoin // = 6
  case actionPlayerQuit // = 7
  case actionVictory // = 8
  case actionDefeat // = 9
  case actionTimedOut // = 10
  case UNRECOGNIZED(Int)

  init() {
    self = .actionUnset
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .actionUnset
    case 1: self = .actionAttack
    case 2: self = .actionDodge
    case 3: self = .actionSpecialAttack
    case 4: self = .actionSwapPokemon
    case 5: self = .actionFaint
    case 6: self = .actionPlayerJoin
    case 7: self = .actionPlayerQuit
    case 8: self = .actionVictory
    case 9: self = .actionDefeat
    case 10: self = .actionTimedOut
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .actionUnset: return 0
    case .actionAttack: return 1
    case .actionDodge: return 2
    case .actionSpecialAttack: return 3
    case .actionSwapPokemon: return 4
    case .actionFaint: return 5
    case .actionPlayerJoin: return 6
    case .actionPlayerQuit: return 7
    case .actionVictory: return 8
    case .actionDefeat: return 9
    case .actionTimedOut: return 10
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension POGOProtos_Data_Battle_BattleActionType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [POGOProtos_Data_Battle_BattleActionType] = [
    .actionUnset,
    .actionAttack,
    .actionDodge,
    .actionSpecialAttack,
    .actionSwapPokemon,
    .actionFaint,
    .actionPlayerJoin,
    .actionPlayerQuit,
    .actionVictory,
    .actionDefeat,
    .actionTimedOut,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension POGOProtos_Data_Battle_BattleActionType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACTION_UNSET"),
    1: .same(proto: "ACTION_ATTACK"),
    2: .same(proto: "ACTION_DODGE"),
    3: .same(proto: "ACTION_SPECIAL_ATTACK"),
    4: .same(proto: "ACTION_SWAP_POKEMON"),
    5: .same(proto: "ACTION_FAINT"),
    6: .same(proto: "ACTION_PLAYER_JOIN"),
    7: .same(proto: "ACTION_PLAYER_QUIT"),
    8: .same(proto: "ACTION_VICTORY"),
    9: .same(proto: "ACTION_DEFEAT"),
    10: .same(proto: "ACTION_TIMED_OUT"),
  ]
}
