// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct POGOProtos_Settings_Master_Pokemon_EvolutionBranch {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var evolution: POGOProtos_Enums_PokemonId = .missingno

  var evolutionItemRequirement: POGOProtos_Inventory_Item_ItemId = .itemUnknown

  var candyCost: Int32 = 0

  var kmBuddyDistanceRequirement: Float = 0

  var form: POGOProtos_Enums_Form = .unset

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "POGOProtos.Settings.Master.Pokemon"

extension POGOProtos_Settings_Master_Pokemon_EvolutionBranch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EvolutionBranch"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "evolution"),
    2: .standard(proto: "evolution_item_requirement"),
    3: .standard(proto: "candy_cost"),
    4: .standard(proto: "km_buddy_distance_requirement"),
    5: .same(proto: "form"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.evolution)
      case 2: try decoder.decodeSingularEnumField(value: &self.evolutionItemRequirement)
      case 3: try decoder.decodeSingularInt32Field(value: &self.candyCost)
      case 4: try decoder.decodeSingularFloatField(value: &self.kmBuddyDistanceRequirement)
      case 5: try decoder.decodeSingularEnumField(value: &self.form)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.evolution != .missingno {
      try visitor.visitSingularEnumField(value: self.evolution, fieldNumber: 1)
    }
    if self.evolutionItemRequirement != .itemUnknown {
      try visitor.visitSingularEnumField(value: self.evolutionItemRequirement, fieldNumber: 2)
    }
    if self.candyCost != 0 {
      try visitor.visitSingularInt32Field(value: self.candyCost, fieldNumber: 3)
    }
    if self.kmBuddyDistanceRequirement != 0 {
      try visitor.visitSingularFloatField(value: self.kmBuddyDistanceRequirement, fieldNumber: 4)
    }
    if self.form != .unset {
      try visitor.visitSingularEnumField(value: self.form, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: POGOProtos_Settings_Master_Pokemon_EvolutionBranch, rhs: POGOProtos_Settings_Master_Pokemon_EvolutionBranch) -> Bool {
    if lhs.evolution != rhs.evolution {return false}
    if lhs.evolutionItemRequirement != rhs.evolutionItemRequirement {return false}
    if lhs.candyCost != rhs.candyCost {return false}
    if lhs.kmBuddyDistanceRequirement != rhs.kmBuddyDistanceRequirement {return false}
    if lhs.form != rhs.form {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
