CREATE TABLE IF NOT EXISTS `web_session` (
    `token` varchar(255) NOT NULL,
    `userid` varchar(255) DEFAULT NULL,
    `created` int(11) NOT NULL DEFAULT 0,
    `updated` int(11) NOT NULL DEFAULT 0,
    `idle` int(11) NOT NULL DEFAULT 0,
    `data` text DEFAULT NULL,
    `ipaddress` varchar(255) DEFAULT NULL,
    `useragent` text DEFAULT NULL,
    PRIMARY KEY (`token`)
);
CREATE TABLE IF NOT EXISTS `pokestop` (
    `id` varchar(35) NOT NULL,
    `lat` double(18,14) NOT NULL,
    `lon` double(18,14) NOT NULL,
    `name` varchar(128) DEFAULT NULL,
    `url` varchar(200) DEFAULT NULL,
    `lure_expire_timestamp` int(11) unsigned DEFAULT NULL,
    `last_modified_timestamp` int(11) unsigned DEFAULT NULL,
    `updated` int(11) unsigned NOT NULL,
    `enabled` tinyint(1) unsigned DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `ix_coords` (`lat`,`lon`),
    KEY `ix_lure_expire_timestamp` (`lure_expire_timestamp`),
    KEY `ix_updated` (`updated`)
);
CREATE TABLE IF NOT EXISTS `gym` (
    `id` varchar(35) NOT NULL,
    `lat` double(18,14) NOT NULL,
    `lon` double(18,14) NOT NULL,
    `name` varchar(128) DEFAULT NULL,
    `url` varchar(200) DEFAULT NULL,
    `last_modified_timestamp` int(11) unsigned DEFAULT NULL,
    `raid_end_timestamp` int(11) unsigned DEFAULT NULL,
    `raid_spawn_timestamp` int(11) unsigned DEFAULT NULL,
    `raid_battle_timestamp` int(11) unsigned DEFAULT NULL,
    `updated` int(11) unsigned NOT NULL,
    `raid_pokemon_id` smallint(6) unsigned DEFAULT NULL,
    `guarding_pokemon_id` smallint(6) unsigned DEFAULT NULL,
    `availble_slots` smallint(6) unsigned DEFAULT NULL,
    `team_id` tinyint(3) unsigned DEFAULT NULL,
    `raid_level` tinyint(3) unsigned DEFAULT NULL,
    `enabled` tinyint(1) unsigned DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `ix_coords` (`lat`,`lon`),
    KEY `ix_raid_end_timestamp` (`raid_end_timestamp`),
    KEY `ix_updated` (`updated`)
);
CREATE TABLE IF NOT EXISTS `pokemon` (
    `id` varchar(35) NOT NULL,
    `pokestop_id` varchar(35) DEFAULT NULL,
    `spawn_id` varchar(20) DEFAULT NULL,
    `lat` double(18,14) NOT NULL,
    `lon` double(18,14) NOT NULL,
    `weight` double(18,14) DEFAULT NULL,
    `size` double(18,14) DEFAULT NULL,
    `expire_timestamp` int(11) unsigned DEFAULT NULL,
    `updated` int(11) unsigned DEFAULT NULL,
    `pokemon_id` smallint(6) unsigned NOT NULL,
    `move_1` tinyint(3) unsigned DEFAULT NULL,
    `move_2` tinyint(3) unsigned DEFAULT NULL,
    `gender` tinyint(3) unsigned DEFAULT NULL,
    `cp` smallint(6) unsigned DEFAULT NULL,
    `atk_iv` tinyint(3) unsigned DEFAULT NULL,
    `def_iv` tinyint(3) unsigned DEFAULT NULL,
    `sta_iv` tinyint(3) unsigned DEFAULT NULL,
    `form` tinyint(3) unsigned DEFAULT NULL,
    `level` tinyint(3) unsigned DEFAULT NULL,
    `weather` tinyint(3) unsigned DEFAULT NULL,
    `costume` tinyint(3) unsigned DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `ix_coords` (`lat`,`lon`),
    KEY `ix_pokemon_id` (`pokemon_id`),
    KEY `ix_updated` (`updated`),
    KEY `ix_expire_timestamp` (`expire_timestamp`),
    CONSTRAINT `fk_pokestop_id` FOREIGN KEY (`pokestop_id`) REFERENCES `pokestop`(`id`)
);
