DROP TABLE pokemon;
SET max_heap_table_size = 1024 * 1024 * 1024 * 1;
CREATE TABLE `pokemon` (
 `id` varchar(25) NOT NULL,
 `pokestop_id` varchar(35) DEFAULT NULL,
 `spawn_id` bigint unsigned DEFAULT NULL,
 `lat` double(18,14) NOT NULL,
 `lon` double(18,14) NOT NULL,
 `weight` double(18,14) DEFAULT NULL,
 `size` double(18,14) DEFAULT NULL,
 `expire_timestamp` int unsigned DEFAULT NULL,
 `updated` int unsigned DEFAULT NULL,
 `pokemon_id` smallint unsigned NOT NULL,
 `move_1` smallint unsigned DEFAULT NULL,
 `move_2` smallint unsigned DEFAULT NULL,
 `gender` tinyint unsigned DEFAULT NULL,
 `cp` smallint unsigned DEFAULT NULL,
 `atk_iv` tinyint unsigned DEFAULT NULL,
 `def_iv` tinyint unsigned DEFAULT NULL,
 `sta_iv` tinyint unsigned DEFAULT NULL,
 `form` smallint unsigned DEFAULT NULL,
 `level` tinyint unsigned DEFAULT NULL,
 `weather` tinyint unsigned DEFAULT NULL,
 `costume` tinyint unsigned DEFAULT NULL,
 `first_seen_timestamp` int unsigned NOT NULL,
 `changed` int unsigned NOT NULL DEFAULT '0',
 `iv` float(5,2) unsigned DEFAULT NULL,
 `cell_id` bigint unsigned DEFAULT NULL,
 `expire_timestamp_verified` tinyint unsigned NOT NULL,
 `display_pokemon_id` smallint unsigned DEFAULT NULL,
 `shiny` tinyint(1) DEFAULT '0',
 `username` varchar(32) DEFAULT NULL,
 `capture_1` double(18,14) DEFAULT NULL,
 `capture_2` double(18,14) DEFAULT NULL,
 `capture_3` double(18,14) DEFAULT NULL,
 `pvp_rankings_great_league` VARCHAR(1028),
 `pvp_rankings_ultra_league` VARCHAR(1028),
 `is_event` tinyint unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`,`is_event`),
 KEY `ix_coords` (`lat`,`lon`),
 KEY `ix_pokemon_id` (`pokemon_id`),
 KEY `ix_updated` (`updated`),
 KEY `fk_spawn_id` (`spawn_id`),
 KEY `fk_pokestop_id` (`pokestop_id`),
 KEY `ix_atk_iv` (`atk_iv`),
 KEY `ix_def_iv` (`def_iv`),
 KEY `ix_sta_iv` (`sta_iv`),
 KEY `ix_changed` (`changed`),
 KEY `ix_level` (`level`),
 KEY `fk_pokemon_cell_id` (`cell_id`),
 KEY `ix_expire_timestamp` (`expire_timestamp`),
 KEY `ix_iv` (`iv`)
) ENGINE=MEMORY;
