SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `instance`
	MODIFY COLUMN `name` VARCHAR(255) NOT NULL FIRST;
ALTER TABLE `assignment`
	MODIFY COLUMN `instance_name` VARCHAR(255) NOT NULL AFTER `device_uuid`,
	MODIFY COLUMN `source_instance_name` VARCHAR(255) NULL DEFAULT NULL AFTER `device_group_name`;
SET FOREIGN_KEY_CHECKS=1;
