name: Lint

on: [push, pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.0.1
        with:
          args: --strict
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RUN ESLint
        uses: 123FLO321/action-eslint-standalone@0.4.0
        with:
          args: --ext .js --ext .js.mustache --max-warnings=0
