name: publish

on: [push, release]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@main
    - name: Install Requirements
      run: sudo apt-get -y update &&
           sudo apt-get install -y libcurl4-openssl-dev libmysqlclient-dev &&   
           sudo sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc &&
           sudo cp /usr/bin/convert /usr/local/bin
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build --enable-test-discovery -Xswiftc -g -c debug
    - name: Test
      run: swift test --enable-test-discovery -Xswiftc -g -c debug
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1

      - name: Set .gitsha
        if: github.event_name == 'push'
        run: "echo ${{github.sha}} > .gitsha"
      - name: Set .gitref
        if: github.event_name == 'push'
        run: "echo ${{github.ref}} > .gitref"

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
